### ISSUE TITLE
Map Path

### ISSUE THREAD

**Issue by RaiNote** [dreaddy/SkylordsReplayParserLibrary#1]
Instead of doing this really weird way of reading the map path
`       $mapnamechunk = fread($fp, 150);
       // name of the map. Also includes type
       $replaydata->filename = substr($mapnamechunk,0,strpos($mapnamechunk, ".map")+4);
       $replaydata->mapname = basename($replaydata->filename);
       fseek($fp,0);
       $startpos = sl_seekUntilString( ".map", $fp, -1, true );`
you could just read the first 4 bytes as an integer as it's not the type, it's the length of the string.

**Comment by dreaddy** [comment]
yes that made some problems with some older replays.
But I think I found the problem (less infos stored before the header starts). Fixed&Comitted.
